apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cu0w1k9nk-nodejs
  janus-idp.io/tekton: cu0w1k9nk-nodejs
  backstage.io/kubernetes-id: cu0w1k9nk-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cu0w1k9nk-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
