apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cu0w1k9nk-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cu0w1k9nk-nodejs 
  name: cu0w1k9nk-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: cu0w1k9nk-nodejs 
